Source: https://www.youtube.com/watch?v=GB9ByFAIAH4&list=PLFCB5Dp81iNVmuoGIqcT5oF4K-7kTI5vp&index=7&ab_channel=KeithGalliKeithGalliVerified

### Notes
- NumPy is a multi-dimensional array library. So you can store data in 1D, 2D, 3D, 4D, etc. arrays. 
- Lists vs NumPy: Lists are much slower

## The Basics

In [3]:
import numpy as np

# initializing a 1D array
a = np.array([1, 2, 3]) # or do a = np.array([1, 2, 3], dtype = 'int16')
print(a)


[1 2 3]


In [4]:
# initializing 2D array
b = np.array([[5.0, 6.0, 7.0], [8.0, 9.0, 10.0]])
print(b)

[[ 5.  6.  7.]
 [ 8.  9. 10.]]


In [6]:
# get dimension
b.ndim

2

In [7]:
# get shape (rows and columns)
b.shape

(2, 3)

In [9]:
# get type
a.dtype

dtype('int32')

In [10]:
# get size (will give in terms of bytes of one elem)
a.itemsize

4

In [13]:
# get TOTAL size (in terms of bytes again)
a.size * a.itemsize # or a.nbytes

12

In [12]:
# get num of elems in array
a.size

3

## Accessing/Changing Specific Elems, Rows, Columns, etc.

In [9]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# get a specific elem [r, c]
a[1, 5] # could use neg num for indices too

13

In [18]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# get a specific column
a[:, 0]

array([1, 8])

In [20]:
# getting a lil more fancy lol [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [22]:
# changing one value
a[1, 0] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [20  9 10 11 12 13 14]]


In [23]:
# changing a col of values
a[:, 0] = [20, 21]
print(a)

[[20  2  3  4  5  6  7]
 [21  9 10 11 12 13 14]]


## Initializing Dif Types of Arrays

In [6]:
# all 0's matrix (use np.ones to create a 1's matrix)
np.zeros(5) # just need to specify a shape
np.zeros((2, 3), dtype = 'int32') # to create 2 x 3 matrix of ints

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
# any other number
np.full((2, 2), 11)

array([[11, 11],
       [11, 11]])

In [11]:
# can use full_like if using shape that is already built
np.full_like(a, 7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [12]:
# matrix of random decimal values
np.random.rand(4, 2) # specify shape

array([[0.76412054, 0.81957835],
       [0.79786154, 0.47660336],
       [0.08550631, 0.62472208],
       [0.11123646, 0.53225535]])

In [13]:
# matrix of random integer values
np.random.randint(7, size = (3, 3))

array([[3, 2, 5],
       [5, 1, 6],
       [4, 2, 3]])

In [14]:
# repeat rows to create a matrix
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Recreating Arrays From Images in the Video

In [20]:
output = np.ones((5, 5), dtype = 'int32')

z = np.zeros((3, 3), dtype = 'int32')
z[1, 1] = 9

output[1:4, 1:4] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Careful when copying arrays !

In [21]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [22]:
# to prevent that use the .copy() func
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Mathematics

In [26]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [28]:
a + 2

array([3, 4, 5, 6])

In [30]:
a -=  2 # can also do a/2, a*2, a**2
a

array([-3, -2, -1,  0])

In [31]:
b = np.array([1, 0, 1, 0])
a + b

array([-2, -2,  0,  0])

### Linear Algebra

In [32]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [33]:
# multiply matrices
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [34]:
# find determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [4]:
stats = np.array([[1, 2, 3], [4, 5, 6]])

# to get min
np.min(stats)

1

In [5]:
# can do on a row basis as well
np.max(stats, axis = 0)

array([4, 5, 6])

## Reorganizing Arrays

In [6]:
# want to change array from a 2 x 4 to an 8 x 1
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1)) # can even do 4, 2 or 2, 2, 2 ie. its fine as long as same num of values
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [7]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])